pipeline {
    agent any
    stages {
        stage ('Clean up'){
            steps {
                deleteDir()
            }
        }
        stage('Download'){
            steps {
                bat 'mvn clean install'
            }
        }
        stage('Build') {
            steps {
                bat 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                bat './jenkins/scripts/deliver.bat'
            }
        }
    }
}