pipeline {
    agent any
    stages {
        stage ('Clean up'){
            steps {
                deleteDir()
            }
        }
        stage('Build') {
            steps {
                ps1 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                ps1 'mvn test'
            }
        }
        stage('Deliver') {
            steps {
                ps1 './jenkins/scripts/deliver.ps1'
            }
        }
    }
}
